package com.eeseka.lynk.notification.domain.model

enum class NotificationType {
    PARTICIPANT_INVITED,
    INVITE_CANCELLED,
    REMOVED_FOR_NON_PAYMENT,
    PARTICIPANT_LEFT,

    DETAILS_EDITED,
    SCHEDULE_CHANGED,
    SPOT_CHOSEN,
    VOTING_REOPENED,
    PAYMENTS_ENABLED,

    HANGOUT_STARTED,
    HANGOUT_COMPLETED,
    HANGOUT_CANCELLED,

    PAYMENT_DEADLINE_RESOLVED,
    PAYMENT_DEADLINE_NEEDS_DECISION,
    PAYMENT_DEADLINE_CHANGED,
    PAYOUT_SUCCEEDED,
    PAYOUT_FAILED,
    PAYOUT_NOTHING_TO_SEND,

    PAYMENT_RECEIVED,
    REFUND_ISSUED
}