--
-- PostgreSQL database dump
--


-- Dumped from database version 17.6
-- Dumped by pg_dump version 17.11 (Homebrew)


--
-- Name: hangout_service; Type: SCHEMA; Schema: -; Owner: -
--

CREATE SCHEMA hangout_service;


--
-- Name: notification_service; Type: SCHEMA; Schema: -; Owner: -
--

CREATE SCHEMA notification_service;


--
-- Name: payment_service; Type: SCHEMA; Schema: -; Owner: -
--

CREATE SCHEMA payment_service;


--
-- Name: spot_service; Type: SCHEMA; Schema: -; Owner: -
--

CREATE SCHEMA spot_service;


--
-- Name: user_service; Type: SCHEMA; Schema: -; Owner: -
--

CREATE SCHEMA user_service;


--
-- Name: hangout_participants; Type: TABLE; Schema: hangout_service; Owner: -
--

CREATE TABLE hangout_service.hangout_participants (
    id bigint NOT NULL,
    created_at timestamp(6) with time zone,
    has_paid boolean NOT NULL,
    rsvp_status character varying(255) NOT NULL,
    hangout_id uuid NOT NULL,
    user_id uuid NOT NULL,
    CONSTRAINT hangout_participants_rsvp_status_check CHECK (((rsvp_status)::text = ANY ((ARRAY['ATTENDING'::character varying, 'PENDING'::character varying, 'DECLINED'::character varying])::text[])))
);


--
-- Name: hangout_participants_id_seq; Type: SEQUENCE; Schema: hangout_service; Owner: -
--

ALTER TABLE hangout_service.hangout_participants ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME hangout_service.hangout_participants_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: hangout_users; Type: TABLE; Schema: hangout_service; Owner: -
--

CREATE TABLE hangout_service.hangout_users (
    user_id uuid NOT NULL,
    created_at timestamp(6) with time zone,
    display_name character varying(255) NOT NULL,
    email character varying(255) NOT NULL,
    profile_picture_url character varying(255),
    username character varying(255) NOT NULL
);


--
-- Name: hangouts; Type: TABLE; Schema: hangout_service; Owner: -
--

CREATE TABLE hangout_service.hangouts (
    id uuid NOT NULL,
    chosen_spot_id character varying(255),
    created_at timestamp(6) with time zone,
    description character varying(500),
    host_id uuid NOT NULL,
    max_attendees integer,
    name character varying(100) NOT NULL,
    participant_count integer NOT NULL,
    cost_per_person_kobo bigint,
    payment_deadline timestamp(6) with time zone,
    split_headcount integer,
    payment_state character varying(255),
    total_cost_kobo bigint,
    scheduled_at timestamp(6) with time zone NOT NULL,
    status character varying(255) NOT NULL,
    updated_at timestamp(6) with time zone,
    vibe character varying(255) NOT NULL,
    CONSTRAINT hangouts_payment_state_check CHECK (((payment_state)::text = ANY ((ARRAY['COLLECTING'::character varying, 'AWAITING_HOST_DECISION'::character varying, 'READY_FOR_PAYOUT'::character varying, 'PAYING_OUT'::character varying, 'PAID_OUT'::character varying, 'PAYOUT_FAILED'::character varying])::text[]))),
    CONSTRAINT hangouts_status_check CHECK (((status)::text = ANY ((ARRAY['VOTING'::character varying, 'SCHEDULED'::character varying, 'ONGOING'::character varying, 'COMPLETED'::character varying, 'CANCELLED'::character varying])::text[]))),
    CONSTRAINT hangouts_vibe_check CHECK (((vibe)::text = ANY ((ARRAY['CHILL'::character varying, 'FOOD'::character varying, 'DRINKS'::character varying, 'GAMING'::character varying, 'ACTIVE'::character varying, 'PARTY'::character varying, 'OTHER'::character varying])::text[])))
);


--
-- Name: device_tokens; Type: TABLE; Schema: notification_service; Owner: -
--

CREATE TABLE notification_service.device_tokens (
    id bigint NOT NULL,
    created_at timestamp(6) with time zone,
    platform character varying(255) NOT NULL,
    token character varying(512) NOT NULL,
    user_id uuid NOT NULL,
    CONSTRAINT device_tokens_platform_check CHECK (((platform)::text = ANY ((ARRAY['ANDROID'::character varying, 'IOS'::character varying])::text[])))
);


--
-- Name: device_tokens_id_seq; Type: SEQUENCE; Schema: notification_service; Owner: -
--

ALTER TABLE notification_service.device_tokens ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME notification_service.device_tokens_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: notification_users; Type: TABLE; Schema: notification_service; Owner: -
--

CREATE TABLE notification_service.notification_users (
    user_id uuid NOT NULL,
    created_at timestamp(6) with time zone,
    display_name character varying(255) NOT NULL,
    email character varying(255) NOT NULL
);


--
-- Name: notifications; Type: TABLE; Schema: notification_service; Owner: -
--

CREATE TABLE notification_service.notifications (
    id uuid NOT NULL,
    actor_display_name character varying(255),
    amount_kobo bigint,
    created_at timestamp(6) with time zone,
    hangout_id uuid NOT NULL,
    hangout_name character varying(255) NOT NULL,
    is_read boolean NOT NULL,
    type character varying(255) NOT NULL,
    user_id uuid NOT NULL,
    CONSTRAINT notifications_type_check CHECK (((type)::text = ANY ((ARRAY['PARTICIPANT_INVITED'::character varying, 'INVITE_CANCELLED'::character varying, 'REMOVED_FOR_NON_PAYMENT'::character varying, 'PARTICIPANT_LEFT'::character varying, 'DETAILS_EDITED'::character varying, 'SCHEDULE_CHANGED'::character varying, 'SPOT_CHOSEN'::character varying, 'VOTING_REOPENED'::character varying, 'PAYMENTS_ENABLED'::character varying, 'HANGOUT_STARTED'::character varying, 'HANGOUT_COMPLETED'::character varying, 'HANGOUT_CANCELLED'::character varying, 'PAYMENT_DEADLINE_RESOLVED'::character varying, 'PAYMENT_DEADLINE_NEEDS_DECISION'::character varying, 'PAYMENT_DEADLINE_CHANGED'::character varying, 'PAYOUT_SUCCEEDED'::character varying, 'PAYOUT_FAILED'::character varying, 'PAYOUT_NOTHING_TO_SEND'::character varying, 'PAYMENT_RECEIVED'::character varying, 'REFUND_ISSUED'::character varying])::text[])))
);


--
-- Name: hangout_payout_accounts; Type: TABLE; Schema: payment_service; Owner: -
--

CREATE TABLE payment_service.hangout_payout_accounts (
    id bigint NOT NULL,
    account_holder_name character varying(100) NOT NULL,
    account_number_last4 character varying(4) NOT NULL,
    bank_name character varying(100),
    created_at timestamp(6) with time zone,
    hangout_id uuid NOT NULL,
    host_id uuid NOT NULL,
    paid_out_at timestamp(6) with time zone,
    payout_failure_reason character varying(255),
    recipient_code character varying(100) NOT NULL,
    transfer_reference character varying(100),
    updated_at timestamp(6) with time zone
);


--
-- Name: hangout_payout_accounts_id_seq; Type: SEQUENCE; Schema: payment_service; Owner: -
--

ALTER TABLE payment_service.hangout_payout_accounts ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME payment_service.hangout_payout_accounts_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: payments; Type: TABLE; Schema: payment_service; Owner: -
--

CREATE TABLE payment_service.payments (
    id uuid NOT NULL,
    amount_kobo bigint NOT NULL,
    created_at timestamp(6) with time zone,
    failure_reason character varying(255),
    hangout_id uuid NOT NULL,
    net_amount_kobo bigint NOT NULL,
    paid_at timestamp(6) with time zone,
    reference character varying(100) NOT NULL,
    refund_status character varying(255) NOT NULL,
    refunded_amount_kobo bigint,
    refunded_at timestamp(6) with time zone,
    status character varying(255) NOT NULL,
    updated_at timestamp(6) with time zone,
    user_id uuid NOT NULL,
    CONSTRAINT payments_refund_status_check CHECK (((refund_status)::text = ANY ((ARRAY['NONE'::character varying, 'REQUESTED'::character varying, 'PROCESSED'::character varying, 'FAILED'::character varying])::text[]))),
    CONSTRAINT payments_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'SUCCESS'::character varying, 'FAILED'::character varying, 'ABANDONED'::character varying])::text[])))
);


--
-- Name: user_saved_spots; Type: TABLE; Schema: spot_service; Owner: -
--

CREATE TABLE spot_service.user_saved_spots (
    id bigint NOT NULL,
    category character varying(255) NOT NULL,
    cover_photo_url character varying(2048),
    created_at timestamp(6) with time zone,
    google_place_id character varying(255) NOT NULL,
    latitude double precision NOT NULL,
    longitude double precision NOT NULL,
    name character varying(500) NOT NULL,
    price_level character varying(255),
    short_address character varying(1000),
    user_id uuid NOT NULL,
    CONSTRAINT user_saved_spots_category_check CHECK (((category)::text = ANY ((ARRAY['LOUNGE'::character varying, 'CAFE'::character varying, 'CLUB'::character varying, 'RESTAURANT'::character varying, 'ACTIVITY'::character varying, 'OTHER'::character varying])::text[]))),
    CONSTRAINT user_saved_spots_price_level_check CHECK (((price_level)::text = ANY ((ARRAY['CHEAP'::character varying, 'MODERATE'::character varying, 'EXPENSIVE'::character varying, 'LUXURY'::character varying])::text[])))
);


--
-- Name: user_saved_spots_id_seq; Type: SEQUENCE; Schema: spot_service; Owner: -
--

ALTER TABLE spot_service.user_saved_spots ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME spot_service.user_saved_spots_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: api_keys; Type: TABLE; Schema: user_service; Owner: -
--

CREATE TABLE user_service.api_keys (
    key character varying(255) NOT NULL,
    email character varying(255) NOT NULL,
    expires_at timestamp(6) with time zone NOT NULL,
    valid_from timestamp(6) with time zone NOT NULL
);


--
-- Name: refresh_tokens; Type: TABLE; Schema: user_service; Owner: -
--

CREATE TABLE user_service.refresh_tokens (
    id bigint NOT NULL,
    created_at timestamp(6) with time zone,
    expires_at timestamp(6) with time zone NOT NULL,
    hashed_token character varying(255) NOT NULL,
    user_id uuid NOT NULL
);


--
-- Name: refresh_tokens_id_seq; Type: SEQUENCE; Schema: user_service; Owner: -
--

ALTER TABLE user_service.refresh_tokens ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME user_service.refresh_tokens_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users; Type: TABLE; Schema: user_service; Owner: -
--

CREATE TABLE user_service.users (
    id uuid NOT NULL,
    auth_provider character varying(255) NOT NULL,
    created_at timestamp(6) with time zone,
    display_name character varying(255),
    email character varying(255),
    profile_photo_url character varying(255),
    updated_at timestamp(6) with time zone,
    username character varying(255),
    CONSTRAINT users_auth_provider_check CHECK (((auth_provider)::text = ANY ((ARRAY['GOOGLE'::character varying, 'APPLE'::character varying, 'GUEST'::character varying])::text[])))
);


--
-- Name: hangout_participants hangout_participants_pkey; Type: CONSTRAINT; Schema: hangout_service; Owner: -
--

ALTER TABLE ONLY hangout_service.hangout_participants
    ADD CONSTRAINT hangout_participants_pkey PRIMARY KEY (id);


--
-- Name: hangout_users hangout_users_pkey; Type: CONSTRAINT; Schema: hangout_service; Owner: -
--

ALTER TABLE ONLY hangout_service.hangout_users
    ADD CONSTRAINT hangout_users_pkey PRIMARY KEY (user_id);


--
-- Name: hangouts hangouts_pkey; Type: CONSTRAINT; Schema: hangout_service; Owner: -
--

ALTER TABLE ONLY hangout_service.hangouts
    ADD CONSTRAINT hangouts_pkey PRIMARY KEY (id);


--
-- Name: hangout_participants uk_hangout_participant; Type: CONSTRAINT; Schema: hangout_service; Owner: -
--

ALTER TABLE ONLY hangout_service.hangout_participants
    ADD CONSTRAINT uk_hangout_participant UNIQUE (hangout_id, user_id);


--
-- Name: hangout_users ukgedh2t70schsend201sjxwwvk; Type: CONSTRAINT; Schema: hangout_service; Owner: -
--

ALTER TABLE ONLY hangout_service.hangout_users
    ADD CONSTRAINT ukgedh2t70schsend201sjxwwvk UNIQUE (username);


--
-- Name: hangout_users ukrq6fvtqhm9pv40vi0ewp0amf5; Type: CONSTRAINT; Schema: hangout_service; Owner: -
--

ALTER TABLE ONLY hangout_service.hangout_users
    ADD CONSTRAINT ukrq6fvtqhm9pv40vi0ewp0amf5 UNIQUE (email);


--
-- Name: device_tokens device_tokens_pkey; Type: CONSTRAINT; Schema: notification_service; Owner: -
--

ALTER TABLE ONLY notification_service.device_tokens
    ADD CONSTRAINT device_tokens_pkey PRIMARY KEY (id);


--
-- Name: notification_users notification_users_pkey; Type: CONSTRAINT; Schema: notification_service; Owner: -
--

ALTER TABLE ONLY notification_service.notification_users
    ADD CONSTRAINT notification_users_pkey PRIMARY KEY (user_id);


--
-- Name: notifications notifications_pkey; Type: CONSTRAINT; Schema: notification_service; Owner: -
--

ALTER TABLE ONLY notification_service.notifications
    ADD CONSTRAINT notifications_pkey PRIMARY KEY (id);


--
-- Name: device_tokens uk8se1i37nto56x9252rmrit8ib; Type: CONSTRAINT; Schema: notification_service; Owner: -
--

ALTER TABLE ONLY notification_service.device_tokens
    ADD CONSTRAINT uk8se1i37nto56x9252rmrit8ib UNIQUE (token);


--
-- Name: notification_users ukbsavo8un7bj5haiatejprodte; Type: CONSTRAINT; Schema: notification_service; Owner: -
--

ALTER TABLE ONLY notification_service.notification_users
    ADD CONSTRAINT ukbsavo8un7bj5haiatejprodte UNIQUE (email);


--
-- Name: hangout_payout_accounts hangout_payout_accounts_pkey; Type: CONSTRAINT; Schema: payment_service; Owner: -
--

ALTER TABLE ONLY payment_service.hangout_payout_accounts
    ADD CONSTRAINT hangout_payout_accounts_pkey PRIMARY KEY (id);


--
-- Name: payments payments_pkey; Type: CONSTRAINT; Schema: payment_service; Owner: -
--

ALTER TABLE ONLY payment_service.payments
    ADD CONSTRAINT payments_pkey PRIMARY KEY (id);


--
-- Name: hangout_payout_accounts ukabpdsifrm50wsdovuk5v7gwfb; Type: CONSTRAINT; Schema: payment_service; Owner: -
--

ALTER TABLE ONLY payment_service.hangout_payout_accounts
    ADD CONSTRAINT ukabpdsifrm50wsdovuk5v7gwfb UNIQUE (transfer_reference);


--
-- Name: hangout_payout_accounts ukepaw9n3i6bqn6da50bubpk4wj; Type: CONSTRAINT; Schema: payment_service; Owner: -
--

ALTER TABLE ONLY payment_service.hangout_payout_accounts
    ADD CONSTRAINT ukepaw9n3i6bqn6da50bubpk4wj UNIQUE (hangout_id);


--
-- Name: payments ukxqxnoljqu6mkrkwwcnfisx38; Type: CONSTRAINT; Schema: payment_service; Owner: -
--

ALTER TABLE ONLY payment_service.payments
    ADD CONSTRAINT ukxqxnoljqu6mkrkwwcnfisx38 UNIQUE (reference);


--
-- Name: user_saved_spots uk_user_spot; Type: CONSTRAINT; Schema: spot_service; Owner: -
--

ALTER TABLE ONLY spot_service.user_saved_spots
    ADD CONSTRAINT uk_user_spot UNIQUE (user_id, google_place_id);


--
-- Name: user_saved_spots user_saved_spots_pkey; Type: CONSTRAINT; Schema: spot_service; Owner: -
--

ALTER TABLE ONLY spot_service.user_saved_spots
    ADD CONSTRAINT user_saved_spots_pkey PRIMARY KEY (id);


--
-- Name: api_keys api_keys_pkey; Type: CONSTRAINT; Schema: user_service; Owner: -
--

ALTER TABLE ONLY user_service.api_keys
    ADD CONSTRAINT api_keys_pkey PRIMARY KEY (key);


--
-- Name: refresh_tokens refresh_tokens_pkey; Type: CONSTRAINT; Schema: user_service; Owner: -
--

ALTER TABLE ONLY user_service.refresh_tokens
    ADD CONSTRAINT refresh_tokens_pkey PRIMARY KEY (id);


--
-- Name: users uk6dotkott2kjsp8vw4d0m25fb7; Type: CONSTRAINT; Schema: user_service; Owner: -
--

ALTER TABLE ONLY user_service.users
    ADD CONSTRAINT uk6dotkott2kjsp8vw4d0m25fb7 UNIQUE (email);


--
-- Name: users ukr43af9ap4edm43mmtq01oddj6; Type: CONSTRAINT; Schema: user_service; Owner: -
--

ALTER TABLE ONLY user_service.users
    ADD CONSTRAINT ukr43af9ap4edm43mmtq01oddj6 UNIQUE (username);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: user_service; Owner: -
--

ALTER TABLE ONLY user_service.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: idx_hangout_participants_user_id; Type: INDEX; Schema: hangout_service; Owner: -
--

CREATE INDEX idx_hangout_participants_user_id ON hangout_service.hangout_participants USING btree (user_id);


--
-- Name: idx_hangouts_created_at; Type: INDEX; Schema: hangout_service; Owner: -
--

CREATE INDEX idx_hangouts_created_at ON hangout_service.hangouts USING btree (created_at);


--
-- Name: idx_hangouts_host_id; Type: INDEX; Schema: hangout_service; Owner: -
--

CREATE INDEX idx_hangouts_host_id ON hangout_service.hangouts USING btree (host_id);


--
-- Name: idx_device_tokens_user_id; Type: INDEX; Schema: notification_service; Owner: -
--

CREATE INDEX idx_device_tokens_user_id ON notification_service.device_tokens USING btree (user_id);


--
-- Name: idx_notifications_user_id_created_at; Type: INDEX; Schema: notification_service; Owner: -
--

CREATE INDEX idx_notifications_user_id_created_at ON notification_service.notifications USING btree (user_id, created_at);


--
-- Name: idx_payments_hangout_id; Type: INDEX; Schema: payment_service; Owner: -
--

CREATE INDEX idx_payments_hangout_id ON payment_service.payments USING btree (hangout_id);


--
-- Name: idx_payments_user_id; Type: INDEX; Schema: payment_service; Owner: -
--

CREATE INDEX idx_payments_user_id ON payment_service.payments USING btree (user_id);


--
-- Name: idx_saved_spots_user_id_created_at; Type: INDEX; Schema: spot_service; Owner: -
--

CREATE INDEX idx_saved_spots_user_id_created_at ON spot_service.user_saved_spots USING btree (user_id, created_at DESC);


--
-- Name: idx_refresh_tokens_user_token; Type: INDEX; Schema: user_service; Owner: -
--

CREATE INDEX idx_refresh_tokens_user_token ON user_service.refresh_tokens USING btree (user_id, hashed_token);


--
-- Name: hangout_participants fkauf2ojqv8uybiwhad4n38nxvd; Type: FK CONSTRAINT; Schema: hangout_service; Owner: -
--

ALTER TABLE ONLY hangout_service.hangout_participants
    ADD CONSTRAINT fkauf2ojqv8uybiwhad4n38nxvd FOREIGN KEY (user_id) REFERENCES hangout_service.hangout_users(user_id);


--
-- Name: hangout_participants fknf56te4r3qy6ebopb7ehvuvd7; Type: FK CONSTRAINT; Schema: hangout_service; Owner: -
--

ALTER TABLE ONLY hangout_service.hangout_participants
    ADD CONSTRAINT fknf56te4r3qy6ebopb7ehvuvd7 FOREIGN KEY (hangout_id) REFERENCES hangout_service.hangouts(id);


--
-- PostgreSQL database dump complete
--


