spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}

  jpa:
    hibernate:
      ddl-auto: validate

supabase:
  url: ${SUPABASE_URL}

brevo:
  verify-on-startup: true

jwt:
  expiration-minutes: 15

lynk:
  email:
    url: "https://lynk.com.ng"
  rate-limit:
    ip:
      apply-limit: true
    user:
      apply-limit: true
  web-socket:
    allowed-origin: "https://lynk.com.ng"

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false

server:
  forward-headers-strategy: framework

logging:
  level:
    com.eeseka.lynk: INFO