spring:
  application:
    name: lynk

  task:
    scheduling:
      pool:
        size: 4

  data:
    redis:
      host: "redis-15403.c247.eu-west-1-1.ec2.cloud.redislabs.com"
      password: ${REDIS_PASSWORD}
      username: "default"
      port: 15403
      connect-timeout: 5000ms
      timeout: 2000ms

  flyway:
    enabled: true
    locations: classpath:db/migration

  datasource:
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 20000
      idle-timeout: 300000
      max-lifetime: 12000000
      validation-timeout: 5000
      pool-name: SpringBootHikariCP
      data-source-properties:
        prepareThreshold: 5
        preparedStatementCacheQueries: 256
        preparedStatementCacheSizeMiB: 5

        tcpKeepAlive: true
        socketTimeout: 30
        connectTimeout: 10

  rabbitmq:
    host: stingray-01.rmq.cloudamqp.com
    password: ${RABBITMQ_PASSWORD}
    username: mwaaldxc
    ssl:
      enabled: true
    virtual-host: mwaaldxc
    listener:
      simple:
        acknowledge-mode: auto
        concurrency: 1
        max-concurrency: 3
        prefetch: 10
        default-requeue-rejected: true
        retry:
          enabled: true
          initial-interval: 1000ms
          max-interval: 10000ms
          multiplier: 2
          max-retries: 3
    template:
      retry:
        enabled: true
        initial-interval: 1000ms
        max-interval: 10000ms
        multiplier: 2
        max-retries: 3

jwt:
  secret: ${JWT_SECRET_BASE64}

lynk:
  api-key:
    expires-in-days: 365
    admin:
      username: ${ADMIN_USERNAME}
      password: ${ADMIN_PASSWORD}

  auth:
    google:
      client-id: ${GOOGLE_CLIENT_ID}

  email:
    from: hello@lynk.com.ng
    from-name: Lynk
    reply-to: support@lynk.com.ng
    reply-to-name: Lynk Support
    logo-url: "https://vuibgikrlpgizgwjyhlg.supabase.co/storage/v1/object/public/assets/lynk-logo.png"

brevo:
  url: "https://api.brevo.com/v3"
  api-key: ${BREVO_API_KEY}
  verify-on-startup: false

supabase:
  service-key: ${SUPABASE_SERVICE_KEY}

places:
  url: "https://places.googleapis.com/v1"
  api-key: ${GOOGLE_PLACES_KEY}

paystack:
  url: "https://api.paystack.co"
  secret-key: ${PAYSTACK_SECRET_KEY}

bank-logo:
  nigerian-banks-url: "https://nigerianbanks.xyz"
  supermx-url: "https://supermx1.github.io/nigerian-banks-api"

firebase:
  credentials-path: "classpath:firebase-credentials/lynk-firebase-adminsdk.json"

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: never
      probes:
        enabled: true

server:
  port: ${PORT:8080}